---
- name: Customize Windows 11 Pro
  hosts: windows_target
  gather_facts: no
  tasks:
    - name: Activate Windows with provided key
      win_command: slmgr.vbs /ipk 1234-4567-8910-1112-1314-1516
      become: yes
      become_user: Administrator

    - name: Disable Windows Updates
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: NoAutoUpdate
        data: 1
        type: dword
      become: yes
      become_user: Administrator

    - name: Set Power Plan to High Performance
      win_shell: |
        powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c
      become: yes
      become_user: Administrator

    - name: Join Computer to ho.me Domain
      win_command: |
        Add-Computer -DomainName ho.me -Credential (New-Object System.Management.Automation.PSCredential("USERNAME", (ConvertTo-SecureString "PASSWORD" -AsPlainText -Force)))
      become: yes
      become_user: Administrator

    - name: Download and Install GitHub Desktop
      win_get_url:
        url: https://github.com/desktop/desktop/releases/latest/download/GitHubDesktopSetup.exe
        dest: C:\Temp\GitHubDesktopSetup.exe
      become: yes
      become_user: Administrator

    - name: Install GitHub Desktop
      win_command: C:\Temp\GitHubDesktopSetup.exe /S
      become: yes
      become_user: Administrator

    - name: Download and Install Visual Studio Code
      win_get_url:
        url: https://aka.ms/win32-x64-user-stable
        dest: C:\Temp\VSCodeSetup.exe
      become: yes
      become_user: Administrator

    - name: Install Visual Studio Code
      win_command: C:\Temp\VSCodeSetup.exe /verysilent /norestart
      become: yes
      become_user: Administrator

    - name: Download and Install VLC
      win_get_url:
        url: https://www.videolan.org/vlc/download-windows.html
        dest: C:\Temp\VLCSetup.exe
      become: yes
      become_user: Administrator

    - name: Install VLC
      win_command: C:\Temp\VLCSetup.exe /L=1033 /S
      become: yes
      become_user: Administrator

    - name: Download and Install Steam
      win_get_url:
        url: https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe
        dest: C:\Temp\SteamSetup.exe
      become: yes
      become_user: Administrator

    - name: Install Steam
      win_command: C:\Temp\SteamSetup.exe /S
      become: yes
      become_user: Administrator

